apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  local-domain.server: |
    ${LOCAL_DOMAIN}:53 {
      template IN A ${LOCAL_DOMAIN} {
        match ".*[.]${LOCAL_DOMAIN}[.]$"
        answer "{{ .Name }} 60 IN A 127.0.0.1"
      }
    }
