command_timeout = 2000
format = '$directory$git_branch$git_commit$git_state$git_status$azure$line_break$character'
right_format = ''

[azure]
disabled = false
format = '[$symbol ($subscription)]($style) '
symbol = ''
style = 'blue bold'

[terraform]
format = '[$symbol $version:$workspace]($style) '
symbol = ''
